FORMAT: 1A
HOST: http://localhost:8000/

# voila-CDN:replica

Replica server of voila-CDN. The server facing direct request from the users.

# Group Files

The Files endpoint.

## Index Route [/api/files/]

### Get the file list [GET]

+ Response 200 (application/json)

        {
            "files": [
                {
                    "name": ".gitkeep",
                    "type": "inode/x-empty"
                },
                {
                    "name": "amd.txt",
                    "type": "text/plain"
                },
                {
                    "name": "TV6.rmvb",
                    "type": "application/vnd.rn-realmedia-vbr"
                },
                {
                    "name": "Cooking Class.7z",
                    "type": "application/x-7z-compressed"
                },
                {
                    "name": "Phonetiques.flv",
                    "type": "application/x-shockwave-flash"
                },
                {
                    "name": "AppleWWDC2019.mp4",
                    "type": "video/mpeg4"
                }
            ]
        }  

### Upload a file [POST]

+ Request (multipart/form-data)

        document = [FILE]

+ Response 200 (application/json)

        {
            "ok": true,
            "message": "Successfully uploaded the file",
            "status" = 200
        }

+ Response 500 (application/json)

        {
            "ok": false,
            "message": "Failed to upload the file",
            "status" = 500
        }