FORMAT: 1A
HOST: http://localhost:3399/

# voila-CDN:origin

Origin server of voila-CDN. The server that has the files at first, then push to the replica server.

# Group Files

The Files endpoint.

## Index Route [/api/files/]

### Upload a file to the replica servers [POST]

You just need to provide the file name.

+ Request (application/json)

        {
            "fileName": "amd.txt"
        }

+ Response 200 (application/json)

        {
            "Results": [
                {
                    "message": "Pushed the file amd.txt to replica http://localhost:8000/",
                    "ReplicaResult": {
                        "ok": true,
                        "message": "Successfully uploaded the file",
                        "url": "/media/amd.txt"
                    }
                },
                {
                    "message": "Pushed the file amd.txt to replica http://localhost:8001/",
                    "ReplicaResult": {
                        "ok": true,
                        "message": "Successfully uploaded the file",
                        "url": "/media/amd.txt"
                    }
                }
            ]
        }

+ Response 500 (application/json)

        {
            "Results": [
                {
                    "message": "Failed to upload file amd.txt to replica http://localhost:8000/",
                    "ReplicaResult": {
                        "ok": false,
                        "message": "",
                        "url": ""
                    }
                }
            ]
        }

## Local Files Route [/api/files/local]

### Get the local file list [GET]

Get the file list from the Origin server

+ Response 200 (application/json)

        [
            {
                "name": ".gitkeep",
                "type": "inode/x-empty"
            },
            {
                "name": "amd.txt",
                "type": "text/plain"
            },
            {
                "name": "TV6.rmvb",
                "type": "application/vnd.rn-realmedia-vbr"
            },
            {
                "name": "Cooking Class.7z",
                "type": "application/x-7z-compressed"
            },
            {
                "name": "Phonetiques.flv",
                "type": "application/x-shockwave-flash"
            },
            {
                "name": "AppleWWDC2019.mp4",
                "type": "video/mpeg4"
            }
        ]


## Remote Files Route [/api/files/remote]

### Get the Remote file list [GET]

Get the file list from the Replica server

+ Response 200 (application/json)

        {
            "files": [
                {
                    "name": ".gitkeep",
                    "type": "inode/x-empty"
                },
                {
                    "name": "amd.txt",
                    "type": "text/plain"
                },
                {
                    "name": "TV6.rmvb",
                    "type": "application/vnd.rn-realmedia-vbr"
                },
                {
                    "name": "Cooking Class.7z",
                    "type": "application/x-7z-compressed"
                },
                {
                    "name": "Phonetiques.flv",
                    "type": "application/x-shockwave-flash"
                },
                {
                    "name": "AppleWWDC2019.mp4",
                    "type": "video/mpeg4"
                }
            ]
        }