FROM alpine:edge
LABEL maintainer="Valroad <valorad@outlook.com>"

ADD . /www/voila-CDN-replica/
WORKDIR /www/voila-CDN-replica

RUN echo " --- Installing Dependencies --- " \
 && apk update \
 && apk upgrade musl \
 && apk add python3 libmagic uwsgi uwsgi-python3 su-exec \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && ln -s /usr/bin/pip3 /usr/bin/pip \
 && python -m pip install --no-cache-dir --upgrade pip \
 && rm -rf /var/cache/apk/*

RUN echo " --- Collecting Python Wheels --- " \
 && pip install --no-cache-dir -r requirements.txt

RUN echo " --- Django Init --- " \
 && python manage.py migrate
 && python manage.py collectstatic

VOLUME ["/www/voila-CDN-replica/media"]

ENV EXEC_USER=voilaCDN
ENV EXEC_USER_ID=1000
ENV EXEC_PERMISSION=755

EXPOSE 9000

RUN echo " --- Enabling Entry Script --- " \
 && chmod +x "/www/voila-CDN-replica/index.sh"

ENTRYPOINT ["/www/voila-CDN-replica/index.sh"]
CMD uwsgi --json "./uwsgi.json" && /bin/sh