---

apiVersion: v1
kind: Service
metadata:
  name: voila-cdn-replica
  labels:
    app: voila-cdn-replica
spec:
  type: NodePort
  ports:
    - port: 19000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: voila-cdn-replica